baseURL = 'https://oskar-szulc.github.io/quartz-blog/'
languageCode = 'en-us'
title = 'My Blog'
theme = 'PaperMod'

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

googleAnalytics = ""

minify = true

[params]
env = "production"
title = "My Blog"
description = "A personal blog built with Hugo and PaperMod theme"
keywords = ["Blog", "Portfolio", "PaperMod"]
author = "Oskar Szulc"
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false

ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

[params.assets]
# disableHLJS = true # to disable highlight.js
# disableFingerprinting = true
favicon = "<link / abs url>"
favicon16x16 = "<link / abs url>"
favicon32x32 = "<link / abs url>"
apple_touch_icon = "<link / abs url>"
safari_pinned_tab = "<link / abs url>"

# profile-mode
[params.profileMode]
enabled = false # needs to be explicitly set
title = "My Blog"
subtitle = "A personal blog about technology, development, and more"
imageUrl = "<title or url>"
imageWidth = 120
imageHeight = 120
imageTitle = "My image"

[params.homeInfoParams]
Title = "Hi there 👋"
Content = "Welcome to my blog! I write about technology, development, and other interesting topics."

[[params.socialIcons]]
name = "github"
url = "https://github.com/"

[[params.socialIcons]]
name = "linkedin"
url = "https://linkedin.com/"

[params.analytics.google]
SiteVerificationTag = ""

[params.analytics.bing]
SiteVerificationTag = ""

[params.analytics.yandex]
SiteVerificationTag = ""

[menu]
[[menu.main]]
identifier = "categories"
name = "categories"
url = "/categories/"
weight = 10
[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 20
[[menu.main]]
identifier = "archives"
name = "archives"
url = "/archives/"
weight = 30

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses = true
[markup.highlight]
noClasses = false
